# Generated by Django 4.1.5 on 2023-06-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundKid',
            fields=[
                ('kid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.kid')),
                ('location', models.CharField(max_length=255)),
            ],
            bases=('API.kid',),
        ),
        migrations.CreateModel(
            name='MissingKid',
            fields=[
                ('kid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.kid')),
                ('lost_date', models.DateField(blank=True)),
                ('last_known_location', models.CharField(max_length=255)),
                ('still_missing', models.BooleanField()),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
            bases=('API.kid',),
        ),
    ]
