# Generated by Django 4.1.5 on 2023-06-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_notification_time_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='found_kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.foundkid'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='missing_kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.missingkid'),
        ),
    ]
