# Generated by Django 4.1.5 on 2023-06-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
