# Generated by Django 4.1.5 on 2023-06-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_photo_found_kid_alter_photo_missing_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='found_kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.foundkid'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='missing_kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.missingkid'),
        ),
    ]
