# Generated by Django 4.1.5 on 2023-06-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_photo_found_kid_alter_photo_missing_kid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
