# Generated by Django 4.1.5 on 2023-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
