# Generated by Django 4.1.5 on 2023-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_customuser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kid_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
