# Generated by Django 4.1.5 on 2023-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_notification_kid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingkid',
            name='still_missing',
            field=models.BooleanField(default=True),
        ),
    ]
