# Generated by Django 4.2.2 on 2023-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_missingkid_still_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
