# Generated by Django 4.2.2 on 2023-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_customuser_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=14),
        ),
    ]
